# .travis.yml

language: haskell
sudo: false

cache:
  directories:
    - $HOME/.stack

before_install:
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.0.4/stack-1.0.4-linux-x86_64.tar.gz | tar xfz -
  - install -m 555 -D stack-1.0.4-linux-x86_64/stack $HOME/.local/bin/stack
  - export PATH=$HOME/.local/bin:$PATH
  - rm -v */package.yaml    # prevent stack from trying to re-generate the cabal files
  - stack setup

install:
  - stack build hscolour --copy-bins
  - stack build --only-snapshot --flag=nix-paths:allow-relative-paths

script:
  - stack build --pedantic --test --haddock
