# .travis.yml

language: haskell
sudo: false

cache:
  directories:
    - $HOME/.stack

before_install:
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xfz -
  - install -m 555 -D stack-0.1.5.0-x86_64-linux/stack $HOME/.local/bin/stack
  - export PATH=$HOME/.local/bin:$PATH
  - stack setup

install:
  - stack build hscolour --copy-bins
  - stack build --only-snapshot --flag=nix-paths:allow-relative-paths

script:
  - stack build --pedantic --test --haddock
