name:           cabal2nix
version:        "2.0"
synopsis:       Convert Cabal files into Nix build instructions.
author:
  - Peter Simons
  - Andres Loeh
  - Benno Fünfstück
  - Mateusz Kowalczyk
  - Mathijs Kwik
  - Michael Alan Dorman
  - Shea Levy
  - Dmitry Malikov
  - Eric Seidel
  - Nikolay Amiantov
  - Aycan iRiCAN
  - John Wiegley
  - Philipp Hausmann
  - Spencer Janssen
  - William Casarin
  - Adam Vogt
  - Bryan Gardiner
  - Corey O'Connor
  - Cray Elliott
  - Felix Kunzmann
  - Gabriel Ebner
  - Gergely Risko
  - John Albietz
  - John Chee
  - Jussi Maki
  - Mark Laws
  - Mark Wotton
  - Matvey Aksenov
  - Nicolas Rolland
  - Oliver Charles
  - Pascal Wittmann
  - Patrick John Wheeler
  - Raymond Gauthier
  - Renzo Carbonara
  - Sibi
  - Tanner Doshier
  - Tom Hunger
  - Viktar Basharymau
  - danbst
  - karsten gebbert
  - laMudri
  - Александр Цамутали
maintainer:     Peter Simons <simons@cryp.to>
license:        BSD3
license-file:   LICENSE
github:         nixos/cabal2nix
category:       Distribution, Nix
stability:      stable
tested-with:    GHC > 7.10 && < 8.1
description: >
  Convert Cabal files into Nix build instructions. Users of Nix can install the
  latest version by running:

  .

  > nix-env -i cabal2nix

ghc-options:            -Wall

dependencies:
  - aeson < 1
  - ansi-wl-pprint
  - base < 5
  - bytestring
  - Cabal > 1.24
  - containers
  - deepseq >= 1.4
  - directory
  - distribution-nixpkgs
  - filepath
  - hackage-db
  - language-nix
  - lens
  - optparse-applicative
  - pretty >= 1.1.2
  - process
  - SHA
  - split
  - text
  - transformers
  - yaml

library:
  source-dirs: src
  exposed-modules:
    - Distribution.Nixpkgs.Fetch
    - Distribution.Nixpkgs.Haskell
    - Distribution.Nixpkgs.Haskell.BuildInfo
    - Distribution.Nixpkgs.Haskell.Constraint
    - Distribution.Nixpkgs.Haskell.Derivation
    - Distribution.Nixpkgs.Haskell.FromCabal
    - Distribution.Nixpkgs.Haskell.FromCabal.Configuration
    - Distribution.Nixpkgs.Haskell.FromCabal.Flags
    - Distribution.Nixpkgs.Haskell.FromCabal.License
    - Distribution.Nixpkgs.Haskell.FromCabal.Name
    - Distribution.Nixpkgs.Haskell.FromCabal.Normalize
    - Distribution.Nixpkgs.Haskell.FromCabal.PostProcess
    - Distribution.Nixpkgs.Haskell.Hackage
    - Distribution.Nixpkgs.Haskell.OrphanInstances
    - Distribution.Nixpkgs.Haskell.PackageSourceSpec

executables:
  cabal2nix:
    main:               Main.hs
    source-dirs:        cabal2nix
    other-modules:
      - Paths_cabal2nix
    dependencies:
      - cabal2nix

  hackage2nix:
    main:               Main.hs
    source-dirs:        hackage2nix
    other-modules:
      - Paths_cabal2nix
      - HackageGit
      - Stackage
    dependencies:
      - cabal2nix
      - monad-par
      - monad-par-extras
      - mtl
      - stackage-types
      - time
      - utf8-string
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
