# stack.yaml

resolver: nightly-2016-06-09

packages:
  - .
  - location:
      git: git://github.com/peti/distribution-nixpkgs.git
      commit: 944e7ddc143d5763f46c59d9740e3af820e85938
    extra-dep: true

extra-deps:
  - stackage-types-1.2.0
