name:                   lens-construction-helper
version:                "20150830"
synopsis:               Use data-default to create default instances of various types.
description:            Use data-default to create default instances of various types.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
github:                 nixos/cabal2nix
category:               Data, Lenses, Generics

ghc-options:            -Wall

dependencies:
  - base < 5
  - data-default-class
  - lens

library:
  source-dirs:          src
  exposed-modules:
    - Control.Lens.Create
