name:                   hackage2nix
version:                "20150903"
synopsis:               Convert Cabal files into Nix build instructions.
description:            Convert Cabal files into Nix build instructions.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
github:                 nixos/cabal2nix
category:               Distribution

ghc-options:            -Wall

dependencies:
  - base < 5
  - Cabal >= 1.22.2
  - containers
  - deepseq-generics
  - distribution-nixpkgs
  - filepath
  - language-nix
  - lens
  - monad-par
  - monad-par-extras
  - mtl
  - optparse-applicative
  - pretty >= 1.1.2
  - text
  - yaml

executables:
  hackage2nix:
    main:               Main.hs
    source-dirs:        src
    other-modules:
      - Configuration
      - Paths_hackage2nix
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
