name:                   hackage2nix
version:                "20160406"
synopsis:               Generate hackage-packages.nix.
description:            Generate hackage-packages.nix.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
github:                 nixos/cabal2nix
category:               Distribution

ghc-options:            -Wall

dependencies:
  - aeson
  - base < 5
  - bytestring
  - Cabal > 1.24
  - containers
  - deepseq >= 1.4
  - directory
  - distribution-nixpkgs
  - filepath
  - language-nix > 2
  - lens
  - monad-par
  - monad-par-extras
  - mtl
  - optparse-applicative
  - pretty >= 1.1.2
  - SHA
  - split
  - stackage-types
  - text
  - time
  - utf8-string
  - yaml

executables:
  hackage2nix:
    main:               Main.hs
    source-dirs:        src
    other-modules:
      - HackageGit
      - Paths_hackage2nix
      - Stackage
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
