name:                   distribution-nixpkgs
version:                "20150830"
synopsis:               Convert Cabal files into Nix build instructions.
description:            Convert Cabal files into Nix build instructions.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
github:                 nixos/cabal2nix
category:               Distribution

ghc-options:            -Wall

dependencies:
  - aeson
  - base < 5
  - bytestring
  - Cabal >= 1.22.2
  - containers
  - deepseq
  - deepseq-generics
  - directory
  - doctest
  - filepath
  - hackage-db
  - hspec
  - language-nix
  - lens
  - pretty >= 1.1.2
  - process
  - SHA
  - split
  - transformers
  - utf8-string

library:
  source-dirs:       src
  exposed-modules:
    - Distribution.Nixpkgs.Fetch
    - Distribution.Nixpkgs.Haskell
    - Distribution.Nixpkgs.Haskell.BuildInfo
    - Distribution.Nixpkgs.Haskell.Constraint
    - Distribution.Nixpkgs.Haskell.Derivation
    - Distribution.Nixpkgs.Haskell.FromCabal
    - Distribution.Nixpkgs.Haskell.FromCabal.Configuration
    - Distribution.Nixpkgs.Haskell.FromCabal.Configuration.GHC7102
    - Distribution.Nixpkgs.Haskell.FromCabal.Configuration.Maintainers
    - Distribution.Nixpkgs.Haskell.FromCabal.Flags
    - Distribution.Nixpkgs.Haskell.FromCabal.License
    - Distribution.Nixpkgs.Haskell.FromCabal.Name
    - Distribution.Nixpkgs.Haskell.FromCabal.Normalize
    - Distribution.Nixpkgs.Haskell.FromCabal.Platform
    - Distribution.Nixpkgs.Haskell.FromCabal.PostProcess
    - Distribution.Nixpkgs.Haskell.Hackage
    - Distribution.Nixpkgs.Haskell.HackageGit
    - Distribution.Nixpkgs.Haskell.OrphanInstances
    - Distribution.Nixpkgs.Haskell.PackageSourceSpec
    - Distribution.Nixpkgs.License
    - Distribution.Nixpkgs.Meta
    - Distribution.Nixpkgs.PackageMap

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - distribution-nixpkgs
