name:                   cabal2nix
version:                "20150830"
synopsis:               Convert Cabal files into Nix build instructions.
description:            Convert Cabal files into Nix build instructions.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
github:                 nixos/cabal2nix
category:               Distribution

ghc-options:            -Wall

dependencies:
  - Cabal >= 1.22.2
  - ansi-wl-pprint
  - base < 5
  - containers
  - distribution-nixpkgs
  - language-nix
  - lens
  - optparse-applicative
  - pretty >= 1.1.2
  - pretty-show

executables:
  cabal2nix:
    main:               Main.hs
    source-dirs:        src
    other-modules:
      - Paths_cabal2nix
