name:                   language-nix
version:                "20150903"
synopsis:               Data types and useful functions to represent and manipulate the Nix language.
description:            Data types and useful functions to represent and manipulate the Nix language.
maintainer:             Peter Simons <simons@cryp.to>
license:                BSD3
github:                 nixos/cabal2nix
category:               Distribution, Language

ghc-options:            -Wall

dependencies:
  - base < 5
  - deepseq
  - doctest
  - lens
  - pretty >= 1.1.2
  - QuickCheck
  - regex-posix

library:
  source-dirs:       src
  exposed-modules:
    - Language.Nix
    - Language.Nix.Binding
    - Language.Nix.Identifier
    - Language.Nix.Path

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
